language: php
php:
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - CORE_BRANCH=master
  matrix:
    - DB=sqlite

branches:
  only:
    - master

install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh filesystem_quota $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable filesystem_quota
  - cd apps/filesystem_quota/lib
  - gcc -o chown chown.c -DTEST
  - sudo chown root:travis chown
  - sudo chmod 4777 chown

script:
  # execute unit tests
  - cd ../tests
  - phpunit --configuration phpunit.xml

matrix:
  include:
    - php: 7.2
      env: DB=mysql
    - php: 7.2
      env: DB=pgsql
  fast_finish: true
